In [2]:
import torch

In [3]:
### Crating a Tensor

In [4]:
# Creating a 2 Dim Tensor (2 rows and 3 columns)
torch.empty(2,3)

tensor([[-3.0239e+23,  1.6437e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.6904, 0.2085, 0.9241],
        [0.2368, 0.1595, 0.6181]])

In [8]:
# put seed as 200 to fix randomness in torch
torch.manual_seed(200)

In [9]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [11]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [12]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [14]:
### Tensor Shape

In [15]:
x = torch.eye(7)
x.shape

torch.Size([7, 7])

In [16]:
torch.empty_like(x)

tensor([[-3.1643e+23,  1.6437e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

In [17]:
torch.zeros_like(x)

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
x.dtype

torch.float32

In [23]:
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [24]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
x.dtype

torch.float32

In [27]:
x.to(torch.int32)

tensor([[1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1]], dtype=torch.int32)

In [28]:
### Math Operations

In [32]:
x = torch.rand(2,2)
x

tensor([[0.1716, 0.9481],
        [0.6470, 0.9265]])

In [33]:
x+1

tensor([[1.1716, 1.9481],
        [1.6470, 1.9265]])

In [35]:
x-1

tensor([[-0.8284, -0.0519],
        [-0.3530, -0.0735]])

In [36]:
x*100

tensor([[17.1557, 94.8101],
        [64.7023, 92.6457]])

In [37]:
x/2

tensor([[0.0858, 0.4741],
        [0.3235, 0.4632]])

In [38]:
x**2

tensor([[0.0294, 0.8989],
        [0.4186, 0.8583]])

In [45]:
a = torch.tensor([2,1])
b = torch.tensor([2,1])
print("A:-",a,"B:-",b)

A:- tensor([2, 1]) B:- tensor([2, 1])


In [46]:
a+b

tensor([4, 2])

In [52]:
c = torch.tensor([2.1,-1.5])
torch.abs(c)

tensor([2.1000, 1.5000])

In [55]:
c = torch.tensor([1.1,-5.5])
torch.neg(c)

tensor([-1.1000,  5.5000])

In [56]:
torch.round(c)

tensor([ 1., -6.])

In [57]:
torch.clamp(c,min=2,max=3)

tensor([2., 2.])

In [59]:
e = torch.randint(size=(2,3),low=1,high=10)
e

tensor([[6, 8, 8],
        [9, 7, 5]])

In [60]:
torch.sum(e)

tensor(43)

In [ ]:
#Rows
torch.sum(e,dim=0)

tensor([15, 15, 13])

In [63]:
#Col
torch.sum(e,dim=1)

tensor([22, 21])

In [69]:
torch.mean(e.to(torch.float32))

tensor(7.1667)

In [70]:
torch.transpose(e,0,1)

tensor([[6, 9],
        [8, 7],
        [8, 5]])

In [74]:
clone_a = a.clone()
clone_a[0] = 0

In [75]:
clone_a

tensor([0, 1])

In [76]:
a

tensor([2, 1])